heat_template_version: 2016-10-14

description: >
  Heat Template to create a Docker DataCenter Cluster

parameters:
  num_masters:
    type: number
  num_dtrs:
    type: number
  num_user_nodes:
    type: number
  flavor:
    type: string
  image:
    type: string
  network:
    type: string
  subnet:
    type: string
  public_network:
    type: string
    default: public
  root_size:
    type: number
  default_username:
    type: string
  UCP_version:
    type: string
  DTR_version:
    type: string

resources:
  key_pair:
    type: LIB::DDC::Keypair
    properties:
      prefix: { get_param: default_username }

  insert_ssh_key:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      inputs:
      - name: private_key
      config: |
        #!/usr/bin/bash
        echo $private_key > /root/.ssh/id_rsa.raw 
        echo '-----BEGIN RSA PRIVATE KEY-----' > /root/.ssh/id_rsa
        sed 's/ /\n/g' /root/.ssh/id_rsa.raw | sed -n 5,29p >> /root/.ssh/id_rsa
        echo '-----END RSA PRIVATE KEY-----' >> /root/.ssh/id_rsa
        chmod 600 /root/.ssh/id_rsa /root/.ssh/id_rsa.raw

  deploy_insert_ssh:
    type: OS::Heat::SoftwareDeployment
    depends_on: DDC_master_group
    properties:
      config:
        get_resource: insert_ssh_key
      server:
        { get_attr: [ DDC_master_group, resource.0.server ] }
      input_values:
        private_key: { get_attr: [ key_pair, private_key ] }

  install_ddc:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      inputs:
      - name: user
      - name: the_masters
      - name: the_DTRs
      - name: the_usernodes
      - name: DTRnode_names
      - name: cluster_name
      - name: UCP_version
      - name: DTR_version
      - name: DTR_external_name
      - name: DTR_external_ip
      config: 
        get_file: ddc-config.sh

  deploy_ddc:
    type: OS::Heat::SoftwareDeployment
    depends_on: deploy_insert_ssh
    depends_on: DDC_master_group
    depends_on: DDC_DTR_group
    depends_on: DDC_user_nodes
    properties:
      config:
        get_resource: install_ddc
      server:
        { get_attr: [ DDC_master_group, resource.0.server ] }
      input_values:
        user: { get_param: default_username }
        the_masters: { get_attr: [ DDC_master_group, public_ip ] }
        the_DTRs: { get_attr: [ DDC_DTR_group, private_ip ] }
        the_usernodes: { get_attr: [ DDC_user_nodes, public_ip ] }
        DTRnode_names: { get_attr: [ DDC_DTR_group, servername ] }
        DTR_external_name: 
          str_replace:
            params:
               __type__: "dtr"
               __id__: { get_param: "OS::stack_name" }
            template: __id__-__type__
        DTR_external_ip: { get_attr: [ DTR_floatingip, floating_ip_address] }
        cluster_name: { get_param: 'OS::stack_name' }
        UCP_version: { get_param: UCP_version }
        DTR_version: { get_param: DTR_version }

  ddc_sg:
    type: OS::Neutron::SecurityGroup
    properties:
      name:
        str_replace:
          params:
            __prefix__: "sg"
            __id__: { get_param: "OS::stack_name" }
          template: __id__-__prefix__
      description: Ports for DDC
      rules:
      - protocol: icmp
      - protocol: tcp
        port_range_min: 22
        port_range_max: 22
      - protocol: tcp
        port_range_min: 80
        port_range_max: 80
      - protocol: tcp
        port_range_min: 443
        port_range_max: 443
      - protocol: tcp
        port_range_min: 2375
        port_range_max: 2376
      - protocol: tcp
        port_range_min: 4789
        port_range_max: 4789
      - protocol: tcp
        port_range_min: 7946
        port_range_max: 7946
      - protocol: tcp
        port_range_min: 12376
        port_range_max: 12376
      - protocol: tcp
        port_range_min: 12379
        port_range_max: 12386

  DDC_DTR_group:
    type: OS::Heat::ResourceGroup
    depends_on: ddc_sg
    depends_on: DTR_lb_pool
    properties:
      count: { get_param: num_dtrs }
      resource_def:
          type: ddc-node.yaml
          properties:
            flavor: { get_param: flavor }
            image: { get_param: image }
            ssh_key: { get_attr: [ key_pair, name ] }
            sec_groups:
            - "default"
            - str_replace:
                 params:
                   __prefix__: "sg"
                   __id__: { get_param: "OS::stack_name" }
                 template: __id__-__prefix__
            network: { get_param: network }
            root_size: { get_param: root_size }
            server_name:
              str_replace:
                 params:
                    __type__: "dtr"
                    __id__: { get_param: "OS::stack_name" }
                    __index__: "%index%"
                 template: __id__-__type__-__index__
            lb_pool: { get_resource: DTR_lb_pool }

  DDC_master_group:
    type: OS::Heat::ResourceGroup
    depends_on: ddc_sg
    properties:
      count: { get_param: num_masters }
      resource_def:
          type: ddc-node.yaml
          properties:
            flavor: { get_param: flavor }
            image: { get_param: image }
            ssh_key: { get_attr: [ key_pair, name ] }
            sec_groups:
            - "default"
            - str_replace:
                 params:
                   __prefix__: "sg"
                   __id__: { get_param: "OS::stack_name" }
                 template: __id__-__prefix__
            network: { get_param: network }
            root_size: { get_param: root_size }
            server_name:
              str_replace:
                 params:
                    __type__: "master"
                    __id__: { get_param: "OS::stack_name" }
                    __index__: "%index%"
                 template: __id__-__type__-__index__

  DDC_user_nodes:
    type: OS::Heat::ResourceGroup
    depends_on: ddc_sg
    properties:
      count: { get_param: num_user_nodes }
      resource_def:
          type: ddc-node.yaml
          properties:
            flavor: { get_param: flavor }
            image: { get_param: image }
            ssh_key: { get_attr: [ key_pair, name ] }
            sec_groups: 
            - "default"
            - str_replace:
                 params:
                   __prefix__: "sg"
                   __id__: { get_param: "OS::stack_name" }
                 template: __id__-__prefix__
            network: { get_param: network }
            root_size: { get_param: root_size }
            server_name:
              str_replace:
                 params:
                    __type__: "user"
                    __id__: { get_param: "OS::stack_name" }
                    __index__: "%index%"
                 template: __id__-__type__-__index__

  DTR_load_balancer:
    type: OS::Neutron::LBaaS::LoadBalancer
    properties:
      vip_subnet: { get_param: subnet }
      name: 
        str_replace:
          params:
            __type__: "DTR-lb"
            __id__: { get_param: "OS::stack_name" }
          template: __id__-__type__

  DTR_lb_listener:
    type: OS::Neutron::LBaaS::Listener
    properties:
      loadbalancer: { get_resource: DTR_load_balancer }
      protocol: "HTTPS"
      protocol_port: 443
      name:
        str_replace:
          params:
            __type__: "DTR-lb-listen"
            __id__: { get_param: "OS::stack_name" }
          template: __id__-__type__

  DTR_floatingip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: public_network }
      port_id: { get_attr: [DTR_load_balancer, vip_port_id ]}

  DTR_lb_pool:
    type: OS::Neutron::LBaaS::Pool
    properties:
      lb_algorithm: ROUND_ROBIN
      listener: { get_resource: DTR_lb_listener }
      protocol: "HTTPS"
      name:
        str_replace:
          params:
            __type__: "DTR-lb-pool"
            __id__: { get_param: "OS::stack_name" }
          template: __id__-__type__

outputs:
 master_ip:
    value: { get_attr: [ DDC_master_group, public_ip] }
 DTR_ip:
    value: { get_attr: [ DTR_floatingip, floating_ip_address] }
 user_node_ips:
    value: { get_attr: [ DDC_user_nodes, public_ip] }
 public_key:
    value: { get_attr: [ key_pair, public_key ] }
