heat_template_version: 2016-04-08

description: >
  Heat Template to create a Docker DataCenter Cluster

parameters:
  num_masters:
    type: number
  num_dtrs:
    type: number
  num_user_nodes:
    type: number
  flavor:
    type: string
  image:
    type: string
  network:
    type: string
  root_size:
    type: number
  default_username:
    type: string

resources:
  key_pair:
    type: LIB::DDC::Keypair
    properties:
      prefix: { get_param: default_username }

  insert_ssh_key:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      inputs:
      - name: private_key
      config: |
        #!/usr/bin/bash
        echo $private_key > /root/.ssh/id_rsa.raw 
        echo '-----BEGIN RSA PRIVATE KEY-----' > /root/.ssh/id_rsa
        sed 's/ /\n/g' /root/.ssh/id_rsa.raw | sed -n 5,29p >> /root/.ssh/id_rsa
        echo '-----END RSA PRIVATE KEY-----' >> /root/.ssh/id_rsa
        chmod 600 /root/.ssh/id_rsa /root/.ssh/id_rsa.raw

  deploy_insert_ssh:
    type: OS::Heat::SoftwareDeployment
    depends_on: DDC_master_group
    properties:
      config:
        get_resource: insert_ssh_key
      server:
        { get_attr: [ DDC_master_group, resource.0.server ] }
      input_values:
        private_key: { get_attr: [ key_pair, private_key ] }

  install_ddc:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      inputs:
      - name: user
      - name: the_masters
      - name: the_DTRs
      - name: the_usernodes
      - name: cluster_name
      config: |
        #!/usr/bin/bash
        PRIVATE_IP=$(curl -fsSL http://169.254.169.254/latest/meta-data/local-ipv4)
        PUBLIC_IP=$(curl -fsSL http://169.254.169.254/latest/meta-data/public-ipv4)
        exit 0
        docker run --rm -i --name ucp -v /var/run/docker.sock:/var/run/docker.sock docker/ucp install --host-address $PRIVATE_IP --san ddc-1 --san $PUBLIC_IP --admin-username admin --admin-password solidfire
        # Now get the oher masters checked in
        cat << EOF > /tmp/masters.list
          $the_masters
        EOF
        cat << EOF > /tmp/DTRs.list
          $the_DTRs
        EOF
        cat << EOF > /tmp/usernodes.list
          $the_usernodes
        EOF
        docker swarm join-token manager | tail -n +3 > /tmp/manager_join
        docker swarm join-token worker | tail -n +3 > /tmp/worker_join
        chmod 700 /tmp/manager_join /tmp/worker_join
        for master in `sed 's|\[||g;s|]||g;s|u'\''||g;s|'\''||g;s| ||g;s|,|\n|g' /tmp/masters.list | grep -v $PUBLIC_IP`; do
          echo "Connecting DDC master node: " $master
          scp -o StrictHostKeyChecking=no /tmp/manager_join $user@$master:/tmp/manager_join
          ssh -o StrictHostKeyChecking=no $user@$master 'chmod 700 /tmp/manager_join;chown root.root /tmp/manager_join; 
                                                         chown root.root /tmp/manager_join;
                                                         sudo bash /tmp/manager_join '
        done
        for dtr in `sed 's|\[||g;s|]||g;s|u'\''||g;s|'\''||g;s| ||g;s|,|\n|g' /tmp/DTRs.list`; do
          echo "Connecting DDC DTR node: " $dtr
          scp -o StrictHostKeyChecking=no /tmp/worker_join $user@$dtr:/tmp/worker_join
          ssh -o StrictHostKeyChecking=no $user@$dtr 'chmod 700 /tmp/worker_join; chown root.root /tmp/worker_join; 
                                                      chown root.root /tmp/worker_join;
                                                      sudo bash /tmp/worker_join '
        done
        #docker run -it --rm docker/dtr install --dtr-external-url https://ddc-4.pm.solidfire.net --ucp-node ddc-4.pm.solidfire.net --ucp-username admin --ucp-insecure-tls --ucp-url https://172.27.31.149
        for usernode in `sed 's|\[||g;s|]||g;s|u'\''||g;s|'\''||g;s| ||g;s|,|\n|g' /tmp/usernodes.list`; do
          echo "Connecting DDC User node: " $usernode
          scp -o StrictHostKeyChecking=no /tmp/worker_join $user@$usernode:/tmp/worker_join
          ssh -o StrictHostKeyChecking=no $user@$usernode 'chmod 700 /tmp/worker_join; chown root.root /tmp/worker_join; 
                                                           chown root.root /tmp/worker_join;
                                                           sudo bash /tmp/worker_join '
        done

  deploy_ddc:
    type: OS::Heat::SoftwareDeployment
    depends_on: deploy_insert_ssh
    depends_on: DDC_master_group
    depends_on: DDC_DTR_group
    depends_on: DDC_user_nodes
    properties:
      config:
        get_resource: install_ddc
      server:
        { get_attr: [ DDC_master_group, resource.0.server ] }
      input_values:
        user: { get_param: default_username }
        the_masters: { get_attr: [ DDC_master_group, public_ip ] }
        the_DTRs: { get_attr: [ DDC_DTR_group, public_ip ] }
        the_usernodes: { get_attr: [ DDC_user_nodes, public_ip ] }
        cluster_name: { get_param: 'OS::stack_name' }

  ddc_sg:
    type: OS::Neutron::SecurityGroup
    properties:
      name:
        str_replace:
          params:
            __prefix__: "ddc_sg"
            __id__: { get_param: "OS::stack_name" }
          template: __prefix__-__id__
      description: Ports for DDC
      rules:
      - protocol: tcp
        port_range_min: 1
        port_range_max: 65535
      - protocol: udp
        port_range_min: 1
        port_range_max: 65535

  DDC_DTR_group:
    type: OS::Heat::ResourceGroup
    depends_on: ddc_sg
    properties:
      count: { get_param: num_dtrs }
      resource_def:
          type: ddc-node.yaml
          properties:
            node_name: "ddc-dtr-%index%"
            flavor: { get_param: flavor }
            image: { get_param: image }
            ssh_key: { get_attr: [ key_pair, name ] }
            sec_groups:
            - "default"
            - str_replace:
                 params:
                   __prefix__: "ddc_sg"           
                   __id__: { get_param: "OS::stack_name" }
                 template: __prefix__-__id__
            network: { get_param: network }
            root_size: { get_param: root_size }

  DDC_master_group:
    type: OS::Heat::ResourceGroup
    depends_on: ddc_sg
    properties:
      count: { get_param: num_masters }
      resource_def:
          type: ddc-node.yaml
          properties:
            node_name: "ddc-%index%"
            flavor: { get_param: flavor }
            image: { get_param: image }
            ssh_key: { get_attr: [ key_pair, name ] }
            sec_groups:
            - "default"
            - str_replace:
                 params:
                   __prefix__: "ddc_sg"           
                   __id__: { get_param: "OS::stack_name" }
                 template: __prefix__-__id__
            network: { get_param: network }
            root_size: { get_param: root_size }

  DDC_user_nodes:
    type: OS::Heat::ResourceGroup
    depends_on: ddc_sg
    properties:
      count: { get_param: num_user_nodes }
      resource_def:
          type: ddc-node.yaml
          properties:
            node_name: "ddc-user-nodes"
            flavor: { get_param: flavor }
            image: { get_param: image }
            ssh_key: { get_attr: [ key_pair, name ] }
            sec_groups: 
            - "default"
            - str_replace:
                 params:
                   __prefix__: "ddc_sg"           
                   __id__: { get_param: "OS::stack_name" }
                 template: __prefix__-__id__
            network: { get_param: network }
            root_size: { get_param: root_size }

outputs:
 master_ip:
    value: { get_attr: [ DDC_master_group, public_ip] }
 DTR_ips:
    value: { get_attr: [ DDC_DTR_group, public_ip] }
 user_node_ips:
    value: { get_attr: [ DDC_user_nodes, public_ip] }
 public_key:
    value: { get_attr: [ key_pair, public_key ] }
