heat_template_version: 2016-04-08

description: >
  Heat Template to start a CentOS VM, install docker,
  and the DVPs and put it on the external network

parameters:
  flavor:
    type: string
  image:
    type: string
  ssh_key:
    type: string
  sec_groups:
    type: comma_delimited_list
    default:
    - "default"
  network:
    type: string
  public_network:
    type: string
    default: public
  root_type:
    type: string
    default: solidfire
  root_size:
    type: number
  data_volume_size:
    type: number
    default: 3
  data_volume_type:
    type: string
    default: solidfire
  server_name:
    type: string

resources:
  root_vol:
    type: OS::Cinder::Volume
    properties:
      volume_type: { get_param: root_type }
      image: { get_param: image }
      size: { get_param: root_size }
      name: 
        str_replace:
          params:
            __type__: "root"
            __name__: { get_param: server_name }
          template: __name__-__type__

  wait_cloud_init_done:
    type: OS::Heat::WaitCondition
    properties:
      handle: {get_resource: wait_handle}
      count: 1
      timeout: 900

  wait_handle:
    type: OS::Heat::WaitConditionHandle

  reboot_notify:
    type: LIB::DDC::RebootNotify
    properties:
      wait_cli: { get_attr: [wait_handle, curl_cli] }

  config_users:
    type: LIB::DDC::Users

  install_software:
    type: LIB::DDC::SoftwareInstall

  dvp:
    type: LIB::DDC::dvpInstall

  server_init:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: { get_resource: install_software }
        type: multipart
      - config: { get_resource: config_users }
        type: multipart
      - config: { get_resource: dvp }
        type: multipart
      - config: { get_resource: reboot_notify }
        type: multipart

  server:
    type: OS::Nova::Server
    properties:
      block_device_mapping:
        - device_name: vda
          volume_id: { get_resource: root_vol }
          delete_on_termination: false
      flavor: { get_param: flavor }
      key_name: { get_param: ssh_key }
      security_groups: { get_param: sec_groups }
      networks:
        - network: { get_param: network }
      user_data_format: SOFTWARE_CONFIG
      user_data: { get_resource: server_init }
      name: { get_param: server_name }

  datavolume:
    type: OS::Cinder::Volume
    properties:
      size: { get_param: data_volume_size }
      volume_type: { get_param: data_volume_type }
      name: 
        str_replace:
          params:
            __type__: "data"
            __name__: { get_param: server_name }
          template: __name__-__type__

  volume_attachment:
    type: OS::Cinder::VolumeAttachment
    properties:
      volume_id: { get_resource: datavolume }
      instance_uuid: { get_resource: server }
      mountpoint: /dev/vdb

  floatingip:
    type: OS::Nova::FloatingIP
    properties:
      pool: { get_param: public_network }

  floatingipassoc:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: floatingip }
      server_id: { get_resource: server }

  resgister_dns:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: |
        #!/usr/bin/bash
        HOSTNAME=$(curl -fsSL http://169.254.169.254/latest/meta-data/hostname);
        PUBLIC_IP=$(curl -fsSL http://169.254.169.254/latest/meta-data/public-ipv4)
        # our DNS is open, so send an update
        echo "Updating DNS w/:  update add $HOSTNAME 7200 A $PUBLIC_IP"
        nsupdate << EOF
        update add $HOSTNAME 7200 A $PUBLIC_IP
        send
        EOF
        
  deploy_register_dns:
    type: OS::Heat::SoftwareDeployment
    depends_on: wait_cloud_init_done
    depends_on: floatingipassoc
    properties:
      actions: [ 'CREATE' ]
      config: { get_resource: resgister_dns }
      server: { get_resource: server }

  unregister_dns:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: |
        #!/usr/bin/bash
        HOSTNAME=$(curl -fsSL http://169.254.169.254/latest/meta-data/hostname);
        nsupdate << EOF
        update delete $HOSTNAME A
        send
        EOF
        
  deploy_unregister_dns:
    type: OS::Heat::SoftwareDeployment
    depends_on: [ floatingipassoc, server, floatingip ]
    properties:
      actions: [ 'DELETE' ]
      config: { get_resource: unregister_dns }
      server: { get_resource: server }

outputs:
  server:
    description: Server ID
    value: { get_resource: server }
  public_ip:
    description: Server Floating IP address
    value: { get_attr: [ floatingip, ip ] }
  private_ip:
    description: Server Private IP address
    value: { get_attr: [ server, networks, { get_param: network }, 0]}
  servername:
    description: Name of the server
    value: { get_attr: [ server, name ] }
  reported_ip:
    description: The IP address reported by the server once its ready
    value: { get_attr: [wait_cloud_init_done, data] }
