heat_template_version: 2016-04-08

description: >
  This Template will install NetApp Docker Volume Plugin (NDVP) and configure

parameters:
 dvp_endpoint:
   type: string
 dvp_svip:
   type: string
 dvp_account:
   type: string

resources:
  ndvpInstall:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: {get_resource: ndvpConfig}
      - config: {get_resource: ndvpCommands}

  ndvpConfig:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        merge_how: 'dict(recurse_array,no_replace)+list(append)'
        write_files:
          - path: "/etc/netappdvp/config.json"
            permissions: "0644"
            owner: "root"
            content:
              str_replace:
                template: |
                  {
                     "version": 1,
                     "storageDriverName": "solidfire-san",
                     "debug": false,
                     "Endpoint": "n_endpoint",
                     "SVIP": "n_svip",
                     "TenantName": "n_account",
                     "DefaultVolSz": 1,
                     "InitiatorIFace": "default",
                     "Types": [
                         {
                             "Type": "Bronze",
                             "Qos": {
                                 "minIOPS": 100,
                                 "maxIOPS": 200,
                                 "burstIOPS": 400
                             }
                         },
                         {
                             "Type": "Silver",
                             "Qos": {
                                 "minIOPS": 1000,
                                 "maxIOPS": 2000,
                                 "burstIOPS": 2500
                             }
                         },
                         {
                             "Type": "Gold",
                             "Qos": {
                                 "minIOPS": 3000,
                                 "maxIOPS": 4000,
                                 "burstIOPS": 4500
                             }
                         }
                     ]
                  }
                params:
                  n_endpoint: { get_param: dvp_endpoint }
                  n_svip: { get_param: dvp_svip }
                  n_account: { get_param: dvp_account }

  ndvpCommands:
    type: OS::Heat::SoftwareConfig
    properties:
      config:
        str_replace:
          template: |
            #!/bin/bash
            # setup the DVPs
            # we can not do this here. Docker is not running yet. 
            # docker plugin install store/netapp/ndvp-plugin:1.4.0 --alias netapp --grant-all-permissions
          params:
            dummy-param: dummy

outputs:
  OS::stack_id:
    value: {get_resource: ndvpInstall}
