heat_template_version: 2016-10-14

# NOTE: You don't need to pass the parameter explicitly from the
# parent template, it can be specified via the parameter_defaults
# in the resource_registry instead, if you want to override the default
# and/or share values with other templates in the tree.
parameters:
  default_username:
    type: string
    default: ddc
  extra_key:
    type: string
    default:
      - "#--- empty added key ---"

description: >
  This file takes the keys that are passed to the instance and sets it
  up to use those as the keys so root can ssh around the Mesos cluster.
  Then it takes the extra_key passed to it and uses that for the 
  default user (which it got from the passed in default_username).

resources:
  users:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: {get_resource: user_config}
      - config: {get_resource: ssh_config}

  user_config:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        merge_how: 'dict(recurse_array,no_replace)+list(append)'
        system_info:
          default_user:
            name: { get_param: default_username }
        users:
        - default
        - name: ebalduf
          passwd: "$6$oW.qUNNr$48ynDsAwI5e67S0VmiVrvWJoPuGX7WtPluC80WfiD2DV/iarCz8ewVfEtqPiROUXIW6mkjRP5FqdZJx95becH/"
          sudo: ALL=(ALL) NOPASSWD:ALL
          ssh-authorized-keys:
            - "ssh-rsa put-your-key-here"
            - "ssh-rsa put-your-key-here"
        write_files:
          - path: "/tmp/additional_keys"
            owner: "root"
            permissions: "0600"
            content:
              str_replace:
                template: |
                  <%key%>
                params:
                  <%key%>: { get_param: extra_key }

  # Setup ssh key for the extra user to match the key installed for the
  # default user, e.g that provided via the nova keypair on instance boot
  ssh_config:
    type: OS::Heat::SoftwareConfig
    properties:
      config:
        str_replace:
          template: |
            #!/bin/bash
            yum install -y jq
            curl http://169.254.169.254/openstack/2012-08-10/meta_data.json -o /root/meta_data.json
            cat /root/meta_data.json | jq -r ".keys[0].data" >> /root/.ssh/authorized_keys
            cat /tmp/additional_keys >> /home/$user/.ssh/authorized_keys
          params:
            $user: { get_param: default_username }

outputs:
  OS::stack_id:
    value: {get_resource: users}
